require './app/people_controller.rb'
require './app/helpers/data_parser.rb'
require './app/helpers/people_normalizer.rb'
require './app/models/people.rb'
require './app/mappers/city_mapper.rb'
require './app/processor.rb'
